In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
# Broadcasting

arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0, 11)

In [10]:
# Shallow Copy

slice_of_arr = arr[0:6]

slice_of_arr[:] = 99

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
arr_copy = arr.copy()

In [13]:
arr_copy[:] = 200

In [14]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
# mat[row, col]
# mat[row][col]

In [17]:
mat = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [18]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
mat[0]

array([ 5, 10, 15])

In [20]:
mat[2]

array([35, 40, 45])

In [21]:
mat[1][2]

30

In [22]:
mat[1, 2]

30

In [23]:
mat[:2, 1:]

array([[10, 15],
       [25, 30]])

In [24]:
mat[1:, :2]

array([[20, 25],
       [35, 40]])

In [25]:
# Conditional Selection

In [26]:
arr = np.arange(1, 11)

In [27]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [28]:
arr[list(map(lambda x: x % 2 == 0, arr))]

array([ 2,  4,  6,  8, 10])