In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
x = np.array(my_list)

x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

In [5]:
my_matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [8]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
type(1)

int

In [12]:
type(1.0)

float

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
start = 0
end = 1
n_terms = 10

np.linspace(start, end, n_terms)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [17]:
np.linspace(start, end, n_terms + 1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(2, 4) # Uniform distribution

array([[0.53503745, 0.89096276, 0.41205135, 0.51141039],
       [0.38231507, 0.28963489, 0.53596051, 0.14323071]])

In [20]:
np.random.randn(2, 4) # Standard Normal (aka Gaussian) distribution

array([[-0.11577531, -0.17356115, -0.83556872, -0.74036431],
       [ 1.76855012, -0.23480415,  0.75731632,  2.26229175]])

In [21]:
np.random.randint(1, 100)

32

In [23]:
np.random.randint(1, 100, 10)

array([80, 48, 79, 75, 96, 82, 71, 39, 68, 63])

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [25]:
arr.shape

(25,)

In [26]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.reshape(5,5).shape

(5, 5)

In [29]:
arr.reshape(25,1).shape

(25, 1)

In [31]:
arr.dtype

dtype('int64')

In [36]:
ranarr

array([48,  3,  5, 48, 49, 11, 14, 29, 31, 33])

In [34]:
ranarr.max()

49

In [35]:
ranarr.argmax()

4

In [37]:
ranarr.min()

3

In [38]:
ranarr.argmin()

1